-- Site plans: property backdrops and photo-carrying site markers.
--
-- A network layout used to be a schematic on a grid. For a lodge with a handful of
-- chalets that is the wrong picture — the office needs to see the property as it
-- actually sits, with a photo of each building one click away. Three additions get
-- there, all on existing tables:
--
--   1. An asset can be a `backdrop` — the aerial or site image the canvas is drawn on.
--   2. An asset can belong to a specific canvas node via `node_id`, which is what
--      makes "the photos of chalet 3" a query rather than a naming convention.
--   3. A layout can carry the property's real-world coordinates, pasted from a
--      Google Maps or Earth link, so the office can jump from the plan to the map.

-- 1 + 2 -----------------------------------------------------------------------

alter table public.network_layout_assets
  add column if not exists node_id text;

-- Explicit ordering so the office can arrange a chalet's photos deliberately
-- rather than inheriting whatever order they were uploaded in.
alter table public.network_layout_assets
  add column if not exists sort_order integer not null default 0;

-- The original CHECK predates backdrops. Recreate it rather than dropping the
-- guard entirely — a typo'd kind should still fail loudly.
--
-- Found by definition rather than by name: the constraint in migration 020 was
-- declared inline on the column, so its name was generated by Postgres. Guessing
-- that name and guessing wrong is the bad case — the DROP would quietly match
-- nothing, the ADD would succeed alongside it, and every backdrop upload would
-- then fail against a constraint that looks like it was already replaced.
do $$
declare
  con record;
begin
  for con in
    select conname
    from pg_constraint
    where conrelid = 'public.network_layout_assets'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) ilike '%kind%'
  loop
    execute format(
      'alter table public.network_layout_assets drop constraint %I', con.conname
    );
  end loop;
end $$;

alter table public.network_layout_assets
  add constraint network_layout_assets_kind_check
  check (kind in ('sketch', 'photo', 'reference', 'backdrop'));

-- Fetching one marker's gallery is the hot path once a property has 50+ photos.
create index if not exists network_layout_assets_layout_node_idx
  on public.network_layout_assets (layout_id, node_id);

-- 3 ---------------------------------------------------------------------------

alter table public.network_layouts
  add column if not exists location_lat double precision;
alter table public.network_layouts
  add column if not exists location_lng double precision;
-- The place name as Google gave it, so the plan reads "Marula Lodge" and not a
-- pair of decimals.
alter table public.network_layouts
  add column if not exists location_label text not null default '';

-- RLS ------------------------------------------------------------------------
-- Both tables already have "authenticated may read and write" policies from
-- migration 020, and new columns inherit them. Nothing to add: the wireless
-- module guard in the API is what narrows this to wireless staff, exactly as it
-- does for the rest of the layout data.
